# Generated by Django 3.0.4 on 2020-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewVendorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('optional_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=20)),
                ('marketing_incharge_id', models.IntegerField()),
                ('brand_coordinators_id', models.IntegerField()),
                ('pan', models.CharField(max_length=20)),
                ('gst_input', models.CharField(max_length=20)),
                ('portal_accepted_for_listing', models.IntegerField()),
                ('no_multi_portal_fee', models.FloatField()),
                ('insurance', models.CharField(max_length=30)),
                ('no_storage_fee', models.FloatField()),
                ('fair_participation', models.CharField(max_length=20)),
                ('amazon', models.BooleanField()),
                ('flipkart', models.BooleanField()),
                ('paytm', models.BooleanField()),
                ('snapdeal', models.BooleanField()),
                ('tatacliq', models.BooleanField()),
                ('myntra', models.BooleanField()),
                ('vendor_type', models.CharField(max_length=10)),
                ('state_pan', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocumentAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='uploads/vendor_docs/')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_notification_delivered', models.BooleanField()),
                ('ip_address', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
