version: '2'

services:
  vendors_web:
    build: ./vendors
    command: bash -c "python3 ./vendors/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always
      
  nginx:
    build: ./web
    ports:
      - 80:80
    links:
      - vendors_web
    depends_on:
      - vendors_web
